routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index']);

Route::get('pages/sports', function () {
    return view('pages.sports');
});



Route::get('pages/classement', [App\Http\Controllers\TeamController::class, 'classement'])->name('pages.classement');

Route::get('/events/badminton', [App\Http\Controllers\SportController::class, 'badminton'])->name('events.badminton');


Route::get('/events/basket', [App\Http\Controllers\SportController::class, 'basket'])->name('events.basket');


Route::get('/events/futsal', [App\Http\Controllers\SportController::class, 'futsal'])->name('events.futsal');


Route::get('/events/handball', [App\Http\Controllers\SportController::class, 'handball'])->name('events.handball');


Route::get('/events/lazerRun', [App\Http\Controllers\SportController::class, 'lazerRun'])->name('events.lazerRun');


//sumo 
Route::get('/events/sumo', [App\Http\Controllers\SportController::class, 'sumo'])->name('events.sumo');

//TouchRugby
Route::get('/events/TouchRugby', [App\Http\Controllers\SportController::class, 'touchRugby'])->name('events.touchRugby');
//Volley
Route::get('/events/volley', [App\Http\Controllers\SportController::class, 'volley'])->name('events.volley');

//paletsBretons
Route::get('/events/paletsBretons', [App\Http\Controllers\SportController::class, 'paletsBretons'])->name('events.paletsBretons');

//relaisCrossfit
Route::get('/events/relaisCrossfit', [App\Http\Controllers\SportController::class, 'relaisCrossfit'])->name('events.relaisCrossfit');

//relaisMarathon
Route::get('/events/relaisMarathon', [App\Http\Controllers\SportController::class, 'relaisMarathon'])->name('events.relaisMarathon');

//relais

Route::get('/events/relais', [App\Http\Controllers\SportController::class, 'relais'])->name('events.relais');

Route::get('pages/equipes', [App\Http\Controllers\TeamController::class, 'equipes'])->name('pages.equipes');


Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('home', function () {
        return view('pages.home');
    })->name('home');
});

Route::middleware(['admin_or_organizer'])->group(function () {
    Route::get('/dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard.dashboard');
});

//Route [verification.notice] not defined.
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware(['auth'])->name('verification.notice');

Route::get('/theme/{theme}', function ($theme) {
    session(['theme' => $theme]);
    return back();
})->name('theme.switch');

Route::get('pages/settings', function () {
    return view('pages.settings');
})->middleware(['auth'])->name('pages/settings');

Route::get('/dashboard/usersChartData', [\App\Http\Controllers\DashboardController::class, 'usersChartData']);


Route::middleware(['admin_or_organizer'])->group(function () {
    Route::get('/dashboard/users', [\App\Http\Controllers\UserController::class, 'index'])->name('dashboard.dashboard-users');
});

Route::middleware(['admin_or_organizer'])->group(function () {
    Route::get('/dashboard/teams', [\App\Http\Controllers\TeamController::class, 'index'])->name('dashboard.dashboard-teams');
});



Route::get('/dashboard/events', [App\Http\Controllers\EventController::class, 'index'])->name('dashboard.dashboard-event');
Route::get('/dashboard/events/search', [App\Http\Controllers\EventController::class, 'search'])->name('events.search');
Route::put('/dashboard/events/update/{id}', [App\Http\Controllers\EventController::class, 'update'])->name('events.update');
Route::get('/dashboard/events/create', [App\Http\Controllers\EventController::class, 'create'])->name('events.create');
Route::post('/dashboard/events/destroy-selected', [App\Http\Controllers\EventController::class, 'destroySelected'])->name('events.destroySelected');
Route::post('/dashboard/events/store', [App\Http\Controllers\EventController::class, 'store'])->name('events.store');




Route::put('/users/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
Route::delete('/users/{user}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');

Route::post('/dashboard/users/destroy-selected', [App\Http\Controllers\UserController::class, 'destroySelected'])->name('users.destroySelected');

Route::get('/dashboard/users/search', [App\Http\Controllers\UserController::class, 'search'])->name('users.search');

Route::post('/dashboard/users/reset-profile-photo', [App\Http\Controllers\UserController::class, 'resetProfilePhoto'])->name('users.resetProfilePhoto');

Route::get('/dashboard/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');

Route::post('/dashboard/users/store', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');


Route::put('/dashboard/teams/update/{id}', [App\Http\Controllers\TeamController::class, 'update'])->name('teams.update');
Route::get('/dashboard/teams/search', [App\Http\Controllers\TeamController::class, 'search'])->name('teams.search');
//reset  profile photo
Route::post('/dashboard/teams/resetTeamImage', [App\Http\Controllers\TeamController::class, 'resetTeamImage'])->name('teams.resetTeamImage');
// create team
Route::get('/dashboard/teams/create', [App\Http\Controllers\TeamController::class, 'create'])->name('teams.create');
// store team
Route::post('/dashboard/teams/store', [App\Http\Controllers\TeamController::class, 'store'])->name('teams.store');
// destroy team
Route::delete('/dashboard/teams/{team}', [App\Http\Controllers\TeamController::class, 'destroy'])->name('teams.destroy');
// destroy selected team
Route::post('/dashboard/teams/destroy-selected', [App\Http\Controllers\TeamController::class, 'destroySelected'])->name('teams.destroySelected');

//show team 
Route::get('/myteam', [App\Http\Controllers\TeamController::class, 'monequipe'])->name('teams.show');
Route::post('/teams/join', [App\Http\Controllers\TeamController::class, 'joinTeam'])->name('teams.join');
Route::get('/teams/createnew', [App\Http\Controllers\TeamController::class, 'createnew'])->name('teams.createnew');
Route::post('/teams/{team}/leave', [App\Http\Controllers\TeamController::class, 'leaveTeam'])->name('teams.leave');
Route::get('/teams/{team}/edit', [App\Http\Controllers\TeamController::class, 'edit'])->name('teams.edit');


//events

Route::delete('/events/delete/{event_id}', [PhaseController::class, 'delete_event'])->name('delete.event');
Route::delete('/events/destroySelected', [PhaseController::class, 'destroySelected'])->name('destroySelected.event');


//phases
Route::get('/dashboard/phases', [App\Http\Controllers\PhaseController::class, 'index'])->name('dashboard.dashboard-phases');
// search 
Route::get('/dashboard/phases/search', [App\Http\Controllers\PhaseController::class, 'search'])->name('phases.search');
// update
Route::put('/dashboard/phases/update/{id}', [App\Http\Controllers\PhaseController::class, 'update'])->name('phases.update');
// Create
Route::get('/dashboard/phases/create', [App\Http\Controllers\PhaseController::class, 'create_phasenew'])->name('phases.create_phasenew');
// create_phase post
Route::post('/dashboard/phases/store', [App\Http\Controllers\PhaseController::class, 'store'])->name('phases.store');
//destroySelectedPhases
Route::post('/dashboard/phases/destroySelectedPhases', [App\Http\Controllers\PhaseController::class, 'destroySelectedPhases'])->name('phases.destroySelectedPhases');


//groups 
Route::get('/dashboard/groups', [App\Http\Controllers\PhaseController::class, 'index_groups'])->name('dashboard.dashboard-groups');
// search_groups
Route::get('/dashboard/groups/search', [App\Http\Controllers\PhaseController::class, 'search_groups'])->name('groups.search_groups');
// update_groups
Route::put('/dashboard/groups/update/{id}', [App\Http\Controllers\PhaseController::class, 'update_groups'])->name('groups.update_groups');
// create_groupnew
Route::get('/dashboard/groups/create', [App\Http\Controllers\PhaseController::class, 'create_groupnew'])->name('groups.create_groupnew');
// destroySelectedGroups
Route::post('/dashboard/groups/destroySelected', [App\Http\Controllers\PhaseController::class, 'destroySelectedGroups'])->name('groups.destroySelected');
// store_groups
Route::post('/dashboard/groups/store', [App\Http\Controllers\PhaseController::class, 'store_groups'])->name('groups.store_groups');

///dashboard/matches
Route::get('/dashboard/matches', [App\Http\Controllers\PhaseController::class, 'index_matches'])->name('dashboard.dashboard-matches');
// search_matches
Route::get('/dashboard/matches/search', [App\Http\Controllers\PhaseController::class, 'search_matches'])->name('matches.search_matches');
// update_matches
Route::put('/dashboard/matches/update/{id}', [App\Http\Controllers\PhaseController::class, 'update_matches'])->name('matches.update_matches');
// create_matchenew
Route::get('/dashboard/matches/create', [App\Http\Controllers\PhaseController::class, 'create_matchenew'])->name('matches.create_matchenew');
// store_matches
Route::post('/dashboard/matches/store', [App\Http\Controllers\PhaseController::class, 'store_matches'])->name('matches.store_matches');
// destroySelectedMatches
Route::post('/dashboard/matches/destroySelected', [App\Http\Controllers\PhaseController::class, 'destroySelectedMatches'])->name('matches.destroySelectedmatches');

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/pages/classement.blade.php
@extends('layouts.app', ['title' => 'Classement'])
@props(['teams_medaille', 'teams_point'])

@section('content')
<div class="container mx-auto p-6">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow">
        <div class="p-5">
            <h2 class="text-3xl font-bold mb-5 text-gray-900 dark:text-white">Classement général des équipes</h2>

            <p class="mb-8 dark:text-white">Bienvenue sur la page de classement des Jeux de l'URCA 2024 !
                <br>
                Vous pouvez consulter ici les classements par points et par médailles des équipes participantes.



            </p>
            <div class="overflow-x-auto">
                <h1 class="text-2xl font-bold mb-5 text-gray-900 dark:text-white">Classement par Points</h1>
                <p class="mb-8 dark:text-white">Classement par Points : Suivez les performances des équipes à travers les différents sports. Plus une équipe performe, plus elle accumule de points.

                </p>
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">Logo</th>
                            <th scope="col" class="px-6 py-3">Nom</th>
                            <th scope="col" class="px-6 py-3">Membres</th>
                            <th scope="col" class="px-6 py-3">Composante</th>
                            <th scope="col" class="px-6 py-3">Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($teams_point as $team)
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td class="px-6 py-4">
                            @php
                        $colorClass = '';
                        switch ($team->color) {
                            case 'green':
                                $colorClass = 'bg-green-100 text-green-800';
                                break;
                            case 'blue':
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                            case 'red':
                                $colorClass = 'bg-red-100 text-red-800';
                                break;
                            case 'yellow':
                                $colorClass = 'bg-yellow-100 text-yellow-800';
                                break;
                            case 'indigo':
                                $colorClass = 'bg-indigo-100 text-indigo-800';
                                break;
                            case 'purple':
                                $colorClass = 'bg-purple-100 text-purple-800';
                                break;
                            case 'pink':
                                $colorClass = 'bg-pink-100 text-pink-800';
                                break;
                            case 'gray':
                                $colorClass = 'bg-gray-100 text-gray-800';
                                break;
                            default:
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                        }
                    @endphp

                    @if ($team->image_path)
                        <img class="w-10 h-10 rounded-full" src="{{ asset('storage/' . $team->image_path) }}" alt="{{ $team->name }} image">
                    @else
                        <div class="w-10 h-10 rounded-full {{ $colorClass }} flex items-center justify-center">
                            <span class="text-gray-500 text-lg">{{ substr($team->name, 0, 1) }}</span>
                        </div>
                    @endif
                            </td>
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                {{ $team->name }}
                            </th>
                            <td class="px-6 py-4">
                                @foreach ($team->users as $user)
                                    <p>{{ $user->name }}</p> {{-- or any other property of the user --}}
                                @endforeach
                            </td>
                            <td class="px-6 py-4">
                                {{ $team->degree->name }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $team->points }}
                            </td>
                            
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $teams_point->links('components.UI.pagination') }}

                <h1 class="text-2xl font-bold mb-5 text-gray-900 dark:text-white mt-16">Classement par Médailles</h1>

                <p class="mb-8 dark:text-white">Classement par Médailles : Découvrez les équipes qui se distinguent par le nombre de médailles d'or, d'argent et de bronze remportées.</p>

                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">Logo</th>
                            <th scope="col" class="px-6 py-3">Nom</th>
                            <th scope="col" class="px-6 py-3">Membres</th>
                            <th scope="col" class="px-6 py-3">Composante</th>
                            <th scope="col" class="px-6 py-3">Medailles</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($teams_medaille as $team)
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td class="px-6 py-4">
                            @php
                        $colorClass = '';
                        switch ($team->color) {
                            case 'green':
                                $colorClass = 'bg-green-100 text-green-800';
                                break;
                            case 'blue':
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                            case 'red':
                                $colorClass = 'bg-red-100 text-red-800';
                                break;
                            case 'yellow':
                                $colorClass = 'bg-yellow-100 text-yellow-800';
                                break;
                            case 'indigo':
                                $colorClass = 'bg-indigo-100 text-indigo-800';
                                break;
                            case 'purple':
                                $colorClass = 'bg-purple-100 text-purple-800';
                                break;
                            case 'pink':
                                $colorClass = 'bg-pink-100 text-pink-800';
                                break;
                            case 'gray':
                                $colorClass = 'bg-gray-100 text-gray-800';
                                break;
                            default:
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                        }
                    @endphp

                    @if ($team->image_path)
                        <img class="w-10 h-10 rounded-full" src="{{ asset('storage/' . $team->image_path) }}" alt="{{ $team->name }} image">
                    @else
                        <div class="w-10 h-10 rounded-full {{ $colorClass }} flex items-center justify-center">
                            <span class="text-gray-500 text-lg">{{ substr($team->name, 0, 1) }}</span>
                        </div>
                    @endif
                            </td>
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                {{ $team->name }}
                            </th>
                            <td class="px-6 py-4">
                                @foreach ($team->users as $user)
                                    <p>{{ $user->name }}</p> {{-- or any other property of the user --}}
                                @endforeach
                            </td>
                            
                            <td class="px-6 py-4">
                                {{ $team->degree->name }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $team->medailles }}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!-- Pagination -->
            <div class="mt-4">
        {{ $teams_medaille->links('components.UI.pagination') }}
    </div>

        </div>
    </div>
</div>
@endsection

resources/views/pages/equipes.blade.php
@extends('layouts.app', ['title' => 'Liste des Équipes'])

@php
use App\Models\Degree;

$degrees = Degree::all();

@endphp

@section('content')
<div class="container mx-auto p-6">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow">
        <div class="p-5">
            <h2 class="text-3xl font-bold mb-5 text-gray-900 dark:text-white">Liste des Équipes</h2>
            <div class="overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">Logo</th>
                            <th scope="col" class="px-6 py-3">Nom</th>
                            <th scope="col" class="px-6 py-3">Description</th>
                            <th scope="col" class="px-6 py-3">Composante</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($teams as $team)
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <td class="px-6 py-4">
                            @php
                        $colorClass = '';
                        switch ($team->color) {
                            case 'green':
                                $colorClass = 'bg-green-100 text-green-800';
                                break;
                            case 'blue':
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                            case 'red':
                                $colorClass = 'bg-red-100 text-red-800';
                                break;
                            case 'yellow':
                                $colorClass = 'bg-yellow-100 text-yellow-800';
                                break;
                            case 'indigo':
                                $colorClass = 'bg-indigo-100 text-indigo-800';
                                break;
                            case 'purple':
                                $colorClass = 'bg-purple-100 text-purple-800';
                                break;
                            case 'pink':
                                $colorClass = 'bg-pink-100 text-pink-800';
                                break;
                            case 'gray':
                                $colorClass = 'bg-gray-100 text-gray-800';
                                break;
                            default:
                                $colorClass = 'bg-blue-100 text-blue-800';
                                break;
                        }
                    @endphp

                    @if ($team->image_path)
                        <img class="w-10 h-10 rounded-full" src="{{ asset('storage/' . $team->image_path) }}" alt="{{ $team->name }} image">
                    @else
                        <div class="w-10 h-10 rounded-full {{ $colorClass }} flex items-center justify-center">
                            <span class="text-gray-500 text-lg">{{ substr($team->name, 0, 1) }}</span>
                        </div>
                    @endif
                            </td>
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                {{ $team->name }}
                            </th>
                            <td class="px-6 py-4">
                                {{ $team->description }}
                            </td>
                            <td class="px-6 py-4">
                                @foreach ($degrees as $degree)
                                    @if ($degree->id == $team->degree_id)
                                        {{ $degree->name }}
                                    @endif
                                @endforeach
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!-- Pagination -->
            <div class="mt-4">
        {{ $teams->links('components.UI.pagination') }}
    </div>

        </div>
    </div>
</div>
@endsection

resources/views/pages/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/pages/settings.blade.php
{{-- resources/views/pages/home.blade.php --}}

<!-- Status : factorisation -->

@extends('layouts.app', ['title' => 'Paramètres'])

@section('content')
    <main class="flex flex-col justify-center items-center p-4">
        <h1 class="mb-8 text-2xl font-extrabold text-gray-900 dark:text-white md:text-3xl lg:text-4xl">Paramètres</h1>
        
        <div class="card w-96 mb-4">
            <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" value="" class="sr-only peer" id="themeToggle" checked>
                <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
                <span class="ms-3 text-sm font-medium text-gray-900 dark:text-gray-300">Dark Mode</span>
            </label>

            <script>
                document.addEventListener('DOMContentLoaded', (event) => {
                    const themeToggle = document.getElementById('themeToggle');
                    const theme = '{{ Cookie::get('theme', 'light') }}';
                    if (theme === 'dark') {
                        document.documentElement.classList.add('dark');
                        themeToggle.checked = true;
                    } else {
                        document.documentElement.classList.remove('dark');
                        themeToggle.checked = false;
                    }
                });

                const themeToggle = document.getElementById('themeToggle');
                themeToggle.addEventListener('change', toggleTheme);

                function toggleTheme() {
                    var theme = document.documentElement.classList.contains('dark') ? 'light' : 'dark';
                    document.documentElement.classList.toggle('dark', theme === 'dark');
                    themeToggle.checked = theme === 'dark';

                    fetch('/theme/' + theme).catch(console.error);
                }
            </script>
        </div>

        <div class="card w-96 mb-4">
            <form method="POST" action="{{ route('logout') }}">
                @csrf
                <button onclick="event.preventDefault(); this.closest('form').submit();"
                        class="flex items-center justify-center w-full px-4 py-2 text-sm text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                    <svg class="w-4 h-4 me-2 text-gray-100 dark:text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8h11m0 0-4-4m4 4-4 4m-5 3H3a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h3" />
                    </svg>
                    <span>Se déconnecter</span>
                </button>
            </form>
        </div>
    </main>




@endsection

resources/views/pages/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>